services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nettrader
      MYSQL_USER: nettrader_user
      MYSQL_PASSWORD: nettrader_password
    volumes:
      - ./mysql_dump.sql:/docker-entrypoint-initdb.d/mysql_dump.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: nettrader
      DB_USER: nettrader_user
      DB_PASSWORD: nettrader_password
    depends_on:
      - db
      - mailpit
    restart: unless-stopped
    
  python-fetcher:
    build: ./pythonfetch
    command: python3 pynt2markdown.py
    environment:
      DB_HOST: db
      DB_NAME: nettrader
      DB_USER: nettrader_user
      DB_PASSWORD: nettrader_password
      CAPDEB: "10000"
      URLINDEX: "http://app/"
    depends_on:
      - db
      - app
    restart: unless-stopped
    
  python-mailer:
    build: ./pythonfetch
    command: python3 pymailing.py
    environment:
      DB_HOST: db
      DB_NAME: nettrader
      DB_USER: nettrader_user
      DB_PASSWORD: nettrader_password
      CAPDEB: "10000"
      URLINDEX: "http://app/"
      MAIL_HOST: mailpit
      MAIL_PORT: "1025"
      SENDMAIL_FOR_REAL: "1"
    depends_on:
      - db
      - mailpit
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db
    restart: unless-stopped
    
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # Interface Web pour lire les e-mails
      - "1025:1025" # Port SMTP interne utilisé par msmtp
